apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimcrm-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimcrm-web
  template:
    metadata:
      labels:
        app: mimcrm-web
    spec:
      containers:
        - name: web
          image: mimcrm-web:latest
          env:
            - name: VITE_API_URL
              value: http://mimcrm-api:8080
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: mimcrm-web
spec:
  type: LoadBalancer
  selector:
    app: mimcrm-web
  ports:
    - port: 80
      targetPort: 5173
